music/urls.py
from django.conf.urls import url
from .views import DabListView, DabCreateView

app_name = 'music'

urlpatterns = [
    # /music/
    
    url(r'^create/$', DabCreateView.as_view(), name='create'),
    url(r'^$', DabListView.as_view(), name='index'),
    
    #/music/<album_id>
    #url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    
    # #/music/<album_id>/favorite
    # url(r'^(?P<album_id>[0-9]+)/$', views.favorite, name='favorite'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls')),
]

music/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from datetime import timedelta, datetime, date
from django.utils import timezone

from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.album_title + ' - ' + self.artist

class song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favortie = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title
        
class dab(models.Model):
    handle = models.CharField(max_length=250)
    size = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta():
        ordering = ['-timestamp']
    
    def __str__(self):
        return self.handle
    
    def get_absolute_url(self):
        return reverse("music:index")

music/forms.py
from django import forms
from .models import dab
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import CheckboxSelectMultiple

class DabModelForm(forms.ModelForm):
    
    class Meta:
        model = dab
        fields = '__all__'
    
    # def __init__(self, *args, **kwargs):
    #     super(TrickModelForm, self).__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_id = 'id-trickModelForm'
    #     self.helper.form_class = 'form-group'
    #     self.helper.form_method = 'post'
    #     self.helper.form_action = 'tricks:list'
    #     self.helper.helper.add_input(Submit('submit', 'Submit'))

    # def clean_content(self, *args, **kwargs):
    #     content = self.cleaned_data.get("content")
    #     if content == "abc":
    #         raise forms.ValidationError("Cannot be ABC")
    #     return content

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from django.views.generic import ListView, CreateView
from .models import Album, song, dab
from .forms import DabModelForm

# Create your views here.

class DabListView(ListView):
    template_name = "music/dab_list.html"
    context_object_name = "all_dabs"
    
    def get_queryset(self):
        return dab.objects.all()
        
class DabCreateView(CreateView):
    form_class = DabModelForm
    context_object_name = "all_dabs"
    template_name = 'music/dab_create.html'
    
    def get_queryset(self):
        return dab.objects.all()
# def index(request):
#     all_dabs = dab.objects.all()
#     return render(request, 'music/index.html', {'all_dabs': all_dabs})

# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album': album})
#     # try:
#     #     album = Album.objects.get(pk=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does not exist")
    
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album_id.song_set(pk=request.POST['song'])
#     except (KeyError, song.DoesNotExist):
#         return render(request, 'music/index.html', {
#             'all_albums': all_albums,
#             'error_message': "You did not select a valid song",
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save();
#         return render(request, 'music/index.html', {'all_albums': all_albums})

music/templates/music/dab_create.html
{% extends 'music/home.html' %}
{% block title %}Create Dab | {{ block.super }}{% endblock title %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<head>
	<title>Dababase</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!--<link rel="stylesheet" href="userstyle.css">-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
	<style>

		img.bg {
			/* Set rules to fill background */
			min-height: 100%;
			min-width: 1024px;

			/* Set up proportionate scaling */
			width: 100%;
			height: auto;

			/* Set up positioning */
			position: fixed;
			top: 0;
			left: 0;
		}

		@media screen and (max-width: 1024px){
			img.bg {
				left: 50%;
				margin-left: -512px; }
		}

		#page-wrap { position: relative; width: 400px; margin: 50px auto; padding: 20px; background: transparent;}
		p { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }

        #page-wrap2 { position: relative; width: 400px; margin: 50px auto; padding: 20px; background: white; -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 20px SandyBrown; }
		p2 { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }
	</style>
</head>

<body>
    <img src="{% static 'music/images/bg.jpg' %}" class="bg">
    <div id='page-wrap2'>
        <h1>Create Dab</h1>
        {% for feild in form %}
            <div class='fieldWrapper'>
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        {% include "music/form.html" with form=form btn_title='Submit Dab' %}
    </div>
    {% if all_dabs %}
        <h6>Yes</h6>
    {% else %}
        <h6>No</h6>
    {% endif %}
	{% for dab in all_dabs %}
	<div>
	<div id="page-wrap2">
	<p2><u>{{ dab.handle }}</u></p2>
	<p2><center>{{ dab.size }}</center>
	<small class="form-text text-muted">{{ dab.timestamp }}</small>
	</div>
	{% endfor %}
</body>
{% endblock content %}

music/templates/music/dab_list.html
<html lang="en">
{% extends 'music/home.html' %}
{% load static %}

{% block content %}

<head>
	<title>Dababase</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!--<link rel="stylesheet" href="userstyle.css">-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
	<style>

		img.bg {
			/* Set rules to fill background */
			min-height: 100%;
			min-width: 1024px;

			/* Set up proportionate scaling */
			width: 100%;
			height: auto;

			/* Set up positioning */
			position: fixed;
			top: 0;
			left: 0;
		}

		@media screen and (max-width: 1024px){
			img.bg {
				left: 50%;
				margin-left: -512px; }
		}

		#page-wrap { position: relative; width: 400px; margin: 50px auto; padding: 20px; background: transparent;}
		p { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }

        #page-wrap2 { position: relative; width: 400px; margin: 50px auto; padding: 20px; background: white; -moz-box-shadow: 0 0 20px black; -webkit-box-shadow: 0 0 20px black; box-shadow: 0 0 20px SandyBrown; }
		p2 { font: 15px/2 Georgia, Serif; margin: 0 0 30px 0; text-indent: 40px; }
	</style>
</head>

<body>
    
    
    <img src="{% static 'music/images/bg.jpg' %}" class="bg">
    <div id="page-wrap">
        <a href="{% url 'music:create' %}" class="btn btn-default btn-lg btn-block" role="button">Create Dab</a>
    </div>
	{% for dab in all_dabs%}
	
	<div id="page-wrap2">
	<p2><u>{{ dab.handle }}</u></p2>
	<p2><center>{{ dab.size }}</center>
	<small class="form-text text-muted">{{ dab.timestamp }}</small>
	</div>
	{% endfor %}
</body>
{% endblock content %}

music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song {{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}"></label>
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://s-media-cache-ak0.pinimg.com/564x/96/4d/be/964dbe6e0443d25f2d6124473fe483e1.jpg"></img>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/form.html
{% load crispy_forms_tags %}
    <form class='form {% if form_class %}{{ form_class }}{% endif %}' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="{{ btn_title }}"/>
    </form> 

music/templates/music/home.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" > -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <!--<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>-->
    
    
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
    <div class='container'>
      {% block content %}
      {% endblock content %}
    </div>
  </body>
  
</html>

music/templates/music/index.html
{% if all_dabs %}
    <ul>
        {% for dab in all_dabs %}
        <li>{{ dab.handle }} {{ dab.size }}</li>
        {% endfor %}
    </ul>
{% else %}
    <h3>No DABS</h3>
{% endif %}